wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1655708812
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      4: 3.8.13
      5: 0.12.17
      8:
      - 5
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 32
bbox_interval:
  desc: null
  value: 51
bucket:
  desc: null
  value: ''
cache:
  desc: null
  value: ram
cfg:
  desc: null
  value: /home/lab09/Workspace/yolov5/models/yolov5x.yaml
cos_lr:
  desc: null
  value: false
data:
  desc: null
  value: /home/lab09/Workspace/no_name/data.yaml
data_dict:
  desc: null
  value:
    names:
    - Senior,M
    - Senior,W
    - Normal,M
    - Normal,W
    nc: 4
    train: /home/lab09/Workspace/images/train
    val: /home/lab09/Workspace/images/val
device:
  desc: null
  value: ''
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 50
evolve:
  desc: null
  value: 300
exist_ok:
  desc: null
  value: false
freeze:
  desc: null
  value:
  - 0
hyp:
  desc: null
  value:
    anchor_t: 3.98465
    anchors: 2.0
    box: 0.04701
    cls: 0.44909
    cls_pw: 1.16586
    copy_paste: 0.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.01415
    hsv_s: 0.7541
    hsv_v: 0.40028
    iou_t: 0.2
    lr0: 0.00811
    lrf: 0.01123
    mixup: 0.0
    momentum: 0.96827
    mosaic: 0.99192
    obj: 0.85349
    obj_pw: 1.15821
    perspective: 0.0
    scale: 0.45276
    shear: 0.0
    translate: 0.07677
    warmup_bias_lr: 0.11686
    warmup_epochs: 2.82722
    warmup_momentum: 0.94318
    weight_decay: 0.00051
image_weights:
  desc: null
  value: false
imgsz:
  desc: null
  value: 416
label_smoothing:
  desc: null
  value: 0.0
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: age2000_yolov5x_batch32_img416
noautoanchor:
  desc: null
  value: false
noplots:
  desc: null
  value: false
nosave:
  desc: null
  value: true
noval:
  desc: null
  value: true
optimizer:
  desc: null
  value: SGD
patience:
  desc: null
  value: 100
project:
  desc: null
  value: /home/lab09/Workspace/no_name/train_result
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: /home/lab09/Workspace/no_name/train_result/age2000_yolov5x_batch32_img4163
save_period:
  desc: null
  value: 1
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: /home/lab09/Workspace/yolov5/yolov5x.pt
workers:
  desc: null
  value: 8
